/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TiketKA;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NUR FITRIA MELANI
 */
public class Pembelian extends javax.swing.JFrame {

    private void kosongkanform(){
        txtidpemb.setEditable(true);
        txtidpemb.setText(null);
        cbkodeka.setSelectedIndex(0);
        cbidpenump.setSelectedIndex(0);
        txtharga.setText(null);
        txtjml.setText(null);
        txttotal.setText(null);
    }
    
    public void kodekacombo(){
        try{
            String sql = "SELECT * FROM keretaapi";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                cbkodeka.addItem(res.getString("kodeKA"));
            }   
            res.last();
            int jumlah = res.getRow();
        }catch (SQLException e){
        }
    }
    public void idpenumpcombo(){
        try{
            String sql = "SELECT * FROM penumpang";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                cbidpenump.addItem(res.getString("idPenumpang"));
            }   
            res.last();
            int jumlah = res.getRow();
        }catch (SQLException e){
        }
    }
    
    private void tampildata(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("ID Pembelian");
        model.addColumn("Kode Kereta Api");
        model.addColumn("ID Penumpang");
        model.addColumn("Harga Tiket");
        model.addColumn("Jumlah Tiket");
        model.addColumn("Total Harga");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pembelian";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)}); 
            }   
            tabelpemb.setModel(model); 
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    /**
     * Creates new form Pembelian
     */
    public Pembelian() {
        initComponents();
        tampildata();
        kosongkanform();
        kodekacombo();
        idpenumpcombo();
    }

    public void doExit() {
        int confirm = JOptionPane.showConfirmDialog(this,
            "Pesanan akan dibatalkan",
            "Yakin untuk keluar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            Home h = new Home();
            h.setLocationRelativeTo(null);
            h.setVisible(true);
            this.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtjml = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpemb = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cbkodeka = new javax.swing.JComboBox<>();
        cbidpenump = new javax.swing.JComboBox<>();
        txtidpemb = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 3, 36)); // NOI18N
        jLabel1.setText("Detail Pembelian");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 300, 30));

        jLabel2.setText("ID Pembelian");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setText("Kode Kereta Api");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setText("ID Penumpang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setText("Harga Tiket");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel6.setText("Jumlah Tiket");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel7.setText("Total Harga");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 163, -1));
        getContentPane().add(txtjml, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 92, -1));

        txttotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttotalKeyPressed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 153, -1));

        tabelpemb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpemb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpembMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpemb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 426, 750, 160));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        cbkodeka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--" }));
        getContentPane().add(cbkodeka, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        cbidpenump.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--" }));
        getContentPane().add(cbidpenump, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));
        getContentPane().add(txtidpemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 170, -1));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        if(txtidpemb.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, ID Pembelian belum di isi!");
            txtidpemb.requestFocus();
        }
        //else if(txtharga.getText().trim().equals("")){
          //  JOptionPane.showMessageDialog(null, "Maaf, Harga Tiket belum di isi!");
           // txtharga.requestFocus();
        //}
        else{
            try{
                String sql = "INSERT INTO pembelian VALUES ('"+txtidpemb.getText()
                    +"','"+cbkodeka.getSelectedItem()
                    +"','"+cbidpenump.getSelectedItem()
                    +"','"+txtharga.getText()
                    +"','"+txtjml.getText()
                    +"','"+txttotal.getText()+"')";
                java.sql.Connection conn = (Connection)koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil!");
                tampildata();
                kosongkanform();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        this.doExit();
    }//GEN-LAST:event_batalActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE pembelian SET idPemb='"+txtidpemb.getText()
                    +"',kodeKA='"+cbkodeka.getSelectedItem()
                    +"',idPenumpang='"+cbidpenump.getSelectedItem()
                    +"',hargatiket='"+txtharga.getText()
                    +"',jmltiket='"+txtjml.getText()
                    +"',totalharga='"+txttotal.getText()
                    +"' WHERE idPemb='"+txtidpemb.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil!");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampildata();
        kosongkanform();
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM pembelian WHERE idpemb='"+txtidpemb.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil!");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampildata();
        kosongkanform();
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
            h.setLocationRelativeTo(null);
            h.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_keluarActionPerformed

    private void tabelpembMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpembMouseClicked
        // TODO add your handling code here:
        int baris = tabelpemb.rowAtPoint(evt.getPoint());
        String idpm = tabelpemb.getValueAt(baris, 1).toString();
        txtidpemb.setText(idpm);
        String kodeka = tabelpemb.getValueAt(baris, 2).toString();
        cbkodeka.setSelectedItem(kodeka);
        String idpe = tabelpemb.getValueAt(baris, 3).toString();
        cbidpenump.setSelectedItem(idpe);
        String hrg = tabelpemb.getValueAt(baris, 4).toString();
        txtharga.setText(hrg);
        String jml = tabelpemb.getValueAt(baris, 5).toString();
        txtjml.setText(jml);
        String to = tabelpemb.getValueAt(baris, 6).toString();
        txttotal.setText(to);
    }//GEN-LAST:event_tabelpembMouseClicked

    private void txttotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalKeyPressed
        // TODO add your handling code here:
        int Jumlah = Integer.parseInt(txtjml.getText());
        int Harga = Integer.parseInt(txtharga.getText());
        int Total = Jumlah * Harga;
        txttotal.setText(""+ Total);
    }//GEN-LAST:event_txttotalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> cbidpenump;
    private javax.swing.JComboBox<String> cbkodeka;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelpemb;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidpemb;
    private javax.swing.JTextField txtjml;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
